[build]
  command = "pnpm build"

[context.deploy-preview]
  command = "npx prisma generate && pnpm db:push --accept-data-loss --force-reset && pnpm db:seed && pnpm run build"

[context.production]
  command = "npx prisma generate && npx prisma migrate deploy && pnpm run build"
